### ISSUE TITLE
When including --recon_only  in command line call 'ValueError' occurs

### ISSUE THREAD

**Issue by RobertJirsaraie** [PennBBL/qsiprep#107]
Preprocessing ran to completion (first command below), but the recon command gave me a fatal error. I tried multiple attempts to narrow down the bug and it only seems to occur when I include `--recon_only` in my command line call. I could use some help debugging this or realizing what I am doing wrong. I am still new to DWI processing so could use some direction here.

Also, I am wondering whether it is recommended to run preproc and recon together in the same call? Initially I was thinking I should first visually QA the preproc data before running recon.

Preproc Call -- Ran To Completion: 
`singularity run --cleanenv /dfs2/yassalab/rjirsara/ConteCenterScripts/ToolBox/bids_apps/qsiprep/container_qsiprep.simg \ /dfs2/yassalab/rjirsara/ConteCenterScripts/Conte-Two/analyses/HarmonizePilots/bids \
/dfs2/yassalab/rjirsara/ConteCenterScripts/Conte-Two/analyses/HarmonizePilots/apps \
participant --participant_label Pilot2T \
-w /dfs2/yassalab/rjirsara/ConteCenterScripts/Conte-Two/analyses/HarmonizePilots/apps/qsiprep/workflows \
--fs-license-file /dfs2/yassalab/rjirsara/ConteCenterScripts/ToolBox/bids_apps/qsiprep/license_freesurfer.txt \
--b0-motion-corr-to iterative \
--impute-slice-threshold 0 \
--force-spatial-normalization \
--template MNI152NLin2009cAsym \
--force-spatial-normalization \
--output-resolution 2 \
--output-space T1w \
--skip_bids_validation \
--write-graph \
--low-mem \
--longitudinal` 

Recon Call -- Ran Encountering Bug: 
`singularity run --cleanenv /dfs2/yassalab/rjirsara/ConteCenterScripts/ToolBox/bids_apps/qsiprep/container_qsiprep.simg \ /dfs2/yassalab/rjirsara/ConteCenterScripts/Conte-Two/analyses/HarmonizePilots/bids \
/dfs2/yassalab/rjirsara/ConteCenterScripts/Conte-Two/analyses/HarmonizePilots/apps \
participant --participant_label Pilot2T \
-w /dfs2/yassalab/rjirsara/ConteCenterScripts/Conte-Two/analyses/HarmonizePilots/apps/qsiprep/workflows \
--fs-license-file /dfs2/yassalab/rjirsara/ConteCenterScripts/ToolBox/bids_apps/qsiprep/license_freesurfer.txt \
--force-spatial-normalization \
--template MNI152NLin2009cAsym \
--output-resolution 2 \
--low-mem \
--longitudinal \
--recon-spec /dfs2/yassalab/rjirsara/ConteCenterScripts/ToolBox/bids_apps/qsiprep/designs/mrtrix_multishell_msmt.json \
--recon-input /dfs2/yassalab/rjirsara/ConteCenterScripts/Conte-Two/analyses/HarmonizePilots/apps/qsiprep\
--recon_only \`

Command-Line ERROR:

    Running qsirecon version 0.8.0RC3:
      * BIDS dataset path: /dfs2/yassalab/rjirsara/ConteCenterScripts/Conte-Two/analyses/HarmonizePilots/bids.
      * Participant list: ['Pilot2T'].
      * Run identifier: 20200224-012358_f392e093-7bda-4edc-b145-0e2be3b28453.
    
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 1049, in build_recon_workflow
    sloppy=opts.sloppy
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/recon/base.py", line 91, in init_qsirecon_wf
    sloppy=sloppy
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/recon/base.py", line 159, in init_single_subject_wf
    layout = BIDSLayout(recon_input, validate=False, absolute_paths=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 252, in __init__
    indexer.index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 303, in index_metadata
    file_md.update(pl)

ValueError: dictionary update sequence element #0 has length 4; 2 is required

**Comment by mattcieslak** [comment]
Hi Robert,
Could you show the whole command you used?

**Comment by madrig8l** [comment]
Hi, I am encountering the same error. 

my command is:

`singularity run --cleanenv qsiprep-0.8.0.simg --recon-only --recon-spec mrtrix_singleshell_ss3t --recon-input /home/rocinante/projects/qsiprep_testrun/output/ --fs-license-file /home/rocinante/license.txt /home/rocinante/projects/qsiprep_testrun/ /home/rocinante/projects/qsiprep_testrun/recon_out/ participant 
`

with` /home/rocinante/projects/qsiprep_testrun/output/ ` pointint to the results of the previously (no errors) done preprocessing (including Freesurfer).

this returns the message:

> 
> 200331-08:43:16,74 nipype.utils INFO:
> 	 No new version available.
> Process Process-2:
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
>     self.run()
>   File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 944, in build_recon_workflow
>     bids_dir, participant_label=opts.participant_label, bids_validate=False)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/utils/bids.py", line 80, in collect_participants
>     layout = BIDSLayout(str(bids_dir), validate=bids_validate)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 252, in __init__
>     indexer.index_metadata()
>   File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 303, in index_metadata
>     file_md.update(pl)
> ValueError: dictionary update sequence element #0 has length 4; 2 is required

I am happy to provide any additional information / files!

Bastian

**Comment by mattcieslak** [comment]
This should be fixed now. The --recon_only option still requires the `input_dir output_dir participant` arguments on the command line
