### ISSUE TITLE
[BUG] Carpet plot for eddy in html should be transposed

### ISSUE THREAD

**Issue by fredrmag** [PennBBL/qsiprep#120]
Hi,

## Problem
"Carpet plot" when running with eddy as hmc looks like it should be transformed.

qsiprep version: 0.8.0

## Detailed explanation
It is to my understanding that the "carpet plot" produced for the DWI sequence when running with `eddy` as a hmc model is based on the file `my_eddy_output.eddy_outlier_n_sqr_stdev_map`. This file has the following structure ([fsl documentation](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/UsersGuide#Understanding_eddy_output)):
> These are numeric matrices in ASCII format that all have the same general layout. They consist of an initial line of text, after which there is one row for each volume and one column for each slice. Each row corresponding to a b=0 volume is all zeros since eddy don't consider outliers in these. The meaning of the numbers is different for the three files.

In the html report the carpet plot is displayed like this:
![image](https://user-images.githubusercontent.com/21278572/79972912-f2b30200-8496-11ea-90fc-aa6b061a508b.png)

The b0 volumes will have a zero row, which can be seen in the above figure as the first row, and in the middle. So, for time to be in the x axis, should'nt this data matrix be transformed?

If I am right, the changes that needs to be done is to:
https://github.com/PennBBL/qsiprep/blob/fdba005d9e80f5b425d6177f15a3fb0a66ad6853/qsiprep/interfaces/niworkflows.py#L51
where,
```
slice_scores = np.loadtxt(sliceqc_file, skiprows=1)
```
should be changed to:
```
slice_scores = np.loadtxt(sliceqc_file, skiprows=1).T
```

**Comment by mattcieslak** [comment]
I believe you've found a bug! Thank you for pointing this out.
