### ISSUE TITLE
B0 harmonization

### ISSUE THREAD

**Issue by araikes** [PennBBL/qsiprep#124]
Hi @mattcieslak,

I'm having a discussion on the DIPY GitHub about weird DKI outputs on my multi-acquisition dataset (https://github.com/dipy/dipy/issues/2164). One suggestion is that the b0 intensities don't match. I know that one of the preprocessing steps is supposed to b0 harmonization however, I couldn't find the corresponding step in the code (I would assume it should go [here](https://github.com/PennBBL/qsiprep/blob/ae09b791080dfdd9c08936e081096eee015d9ac7/qsiprep/workflows/dwi/merge.py#L338)).

Is b0 harmonization occurring, particularly in the case of concatenating acquisitions?

**Comment by mattcieslak** [comment]
The harmonization happens here https://github.com/PennBBL/qsiprep/blob/ae09b791080dfdd9c08936e081096eee015d9ac7/qsiprep/interfaces/dwi_merge.py#L64. The values used for b0 harmonization when concatenating multiple acquisitions can be found in the output confounds.tsv file, so if you'd like to un-harmonize them you can divide each volume by those values. Your acquisition seems to have very few samples per shell, but I'm not a DKI expert

**Comment by araikes** [comment]
Perfect. Thanks.

**Comment by mattcieslak** [comment]
What was the result? Does the harmonization in qsiprep need to get updated?
