### ISSUE TITLE
[BUG] Error when merging HCP scans

### ISSUE THREAD

**Issue by mattcieslak** [PennBBL/qsiprep#129]
Using the 4 dir98/dir99 AP/PA scans from the HCP protocol. Denoising and harmonization work fine, but an error message appears:

```

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 566, in main
    qsiprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 632, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 164, in run
    self._clean_queue(jobid, graph, result=result)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/images.py", line 120, in _run_interface
    plus_b0_images = self.inputs.b0_images_plus
AttributeError: 'ConcatRPESplitsInputSpec' object has no attribute 'b0_images_plus'
```

**Comment by mattcieslak** [comment]
Add an option for full AP/PA paired data

**Comment by mattcieslak** [comment]
Partially addressed by #132

**Comment by italab03** [comment]
Thank you for making this wonderful software.

I have paired dir68/dir69 AP/PA multi-shell scans.
When I preprocessed the data using qsiprep:0.9.0beta1 with docker container, I faced the following error:

> 200629-16:27:49,277 nipype.workflow WARNING:
> 	 [Node] Error on "qsiprep_wf.single_subject_00300301_wf.sub_00300301_final_merge_wf.distortion_merger" (/wd/qsiprep_wf/single_subject_00300301_wf/sub_00300301_final_merge_wf/distortion_merger)
> 200629-16:27:50,983 nipype.workflow ERROR:
> 	 Node distortion_merger failed to run on host cb064a6d8111.
> 200629-16:27:51,8 nipype.workflow ERROR:
> 	 Saving crash info to /out/qsiprep/sub-00300301/log/20200629-094838_9231d587-a471-4a7a-a32a-2f3a9257c56e/crash-20200629-162751-root-distortion_merger-87492890-543d-4ef7-ae9a-8497068a4206.txt
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
>     runtime = self._run_interface(runtime)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/dwi_merge.py", line 60, in _run_interface
>     self.inputs.harmonize_b0_intensities)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/dwi_merge.py", line 413, in harmonize_b0s
>     b0_mean = index_img(dwi_nii, b0_indices).get_fdata().mean()
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/image/image.py", line 642, in index_img
>     imgs = check_niimg_4d(imgs)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 356, in check_niimg_4d
>     dtype=dtype)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 276, in check_niimg
>     raise DimensionError(len(niimg.shape), ensure_ndim)
> nilearn._utils.exceptions.DimensionError: Input data has incompatible dimensionality: Expected dimension is 4D and you provided a 3D image. See http://nilearn.github.io/manipulating_images/input_output.html.
> 

Could you tell me how to solve it.

The command used in the analysis is

> docker run -ti --rm -v /mnt/ocean/sourcedata:/data:ro \
> -v /home/test/OCEAN/derivatives/Preprocessed:/out \
> -v /home/test/OCEAN/derivatives/Preprocessed:/wd \
> -v /usr/local/freesurfer/license.txt:/license.txt:ro \
> pennbbl/qsiprep:0.9.0beta1 /data /out participant \
> --participant_label 00300301 \
> --fs-license-file /license.txt \
> --hmc_model eddy \
> --output-resolution 1.7 --output-space T1w \
> --force-spatial-normalization --write-graph \
> -v --b0-threshold 100 \
> -w /wd \
> --combine-all-dwis --distortion-group-merge concat --unringing-method mrdegibbs

`
Thank you in advance.

**Comment by mattcieslak** [comment]
I've seen this one, it will be fixed in 0.9.0beta2. If you switch to "--distortion-group-merge average" it will mimic what the HCP diffusion pipeline does and should finish without any errors. If you're sure you'd rather concat, look out for beta2. Sorry about that!

**Comment by bwinsto2** [comment]
hi @mattcieslak - I'm experiencing a similar issue with HCP unprocessed data that have been BIDSified. Perhaps you could help out. I get an error on rpe_concat despite using `--distortion-group-merge average`

**Command:**
```
singularity run --cleanenv -B /hpc900:/hpc900 qsiprep-0.11.0.sif /hpc900/test_data /hpc900/bwinston/qsiprep/output participant --work_dir/hpc900/bwinston/qsiprep/work_dir --fs-license-file /hpc900/bwinston/license.txt --output-resolution 1.25 --output-space T1w --distortion-group-merge average --participant-label 784565
```
**Crash:**
```
Node: qsiprep_wf.single_subject_784565_wf.dwi_preproc_wf.pre_hmc_wf.rpe_concat
Working directory: /hpc900/bwinston/qsiprep/work_dir/qsiprep_wf/single_subject_784565_wf/dwi_preproc_wf/pre_hmc_wf/rpe_concat

Node inputs:

b0_refs = <undefined>
b0_threshold = 100
bids_dwi_files = <undefined>
bval_files = <undefined>
bvec_files = <undefined>
denoising_confounds = <undefined>
dwi_files = <undefined>
harmonize_b0_intensities = True
raw_concatenated_files = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/dwi_merge.py", line 120, in _run_interface
    pos_merged_nii = math_img('np.clip(img, 0, None)', img=merged_nii)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/image/image.py", line 887, in math_img
    result = eval(formula, data_dict)
  File "<string>", line 1, in <module>
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1818, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
MemoryError: Input formula couldn't be processed, you provided 'np.clip(img, 0, None)',
```

Is the `--distortion-group-merge average` not registering? Any help is appreciated :)

**Comment by mattcieslak** [comment]
@bwinsto2 is there any way I could test on your data? I've got it working on HCP data locally so maybe it's BIDS-related

**Comment by bwinsto2** [comment]
@mattcieslak thanks for the kind offer - I have been trying to troubleshoot this for the past few days. Ultimately, I fixed the above issue, but I am running into a new error. I think it is BIDS related, as you say. EDDY fails, and part of the message is `AcqPara::AcqPara: Unrealistic read-out time`. Our HCP DWI json files have `"TotalReadoutTime" = 0.6`. [According to this](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=fsl;d552bccb.1312), EDDY accepts readouts of 10-200ms. Now, I'm not sure if FSL's definition of readout time is the same as the BIDS definition. If they are the same, there may be an issue with our dataset since 600ms is clearly outside the normal range. 

Since you have it working locally, what do your HCP jsons look like? One example of ours is:
```
"EffectiveEchoSpacing": 0.00078,
"TotalReadoutTime": 0.6,
"PhaseEncodingDirection": "i-",
"EchoTime": 0.0895
```

Thanks so much.

**Comment by mattcieslak** [comment]
Did you use a new working directory with the new parameters? It's possible it's still picking up a cached version with your old totalreadouttime

**Comment by bwinsto2** [comment]
Indeed. Doing a fresh run after fixing the TotalReadoutTime fixed this particular issue. Thank you!
