### ISSUE TITLE
5TT image for anatomically constrained tractography?

### ISSUE THREAD

**Issue by robmcc10** [PennBBL/qsiprep#130]
Hi,

I have ran qsiprep including the `mrtrix_singleshell_ss3t` recon pipeline.
In addition to the tractogram generated byt, I wish to generate some additional tractograms with different options. I intend to use the `space-T1w_desc-preproc_space-T1w_desc-wmFODmtnormed_ss3tcsd.mif.gz` file for this purpose.

I wish to first run tckgen with ACT, for which I require a 5TT image. I assume a 5TT image is available or easily produced from the qsiprep outputs as ACT will have been undertaken as part of the recon pipeline? I can’t seem to find it though - Should I just combine the `qsiprep/sub-[]/anat/sub-[]_label-CSF_probseg.nii.gz, sub-[]_label-WM_probseg.nii.gz, sub-[]_label-GM_probseg.nii.gz` volumes into a 4D file - Im not sure if this would work though as it seems cortical and subcortical GM should be in different volumes?

Thanks,

Rob

**Comment by xiaosonghe** [comment]
My personal experience is, most of the intermediate files that you may be interested in, for instance, you want to redo a few steps with your own settings, are saved in the qsirecon_wf folder. Refer to your log file you should be able to find them, at least most of them. Good luck! And Matt feel free to correct me if I am wrong!

**Comment by robmcc10** [comment]
thank you! Yes if anyonne else looking for it it is in this folder:
qsi_working_dir/qsirecon_wf/sub-_mrtrix_msmt/anat_ingress_wf/create_5tt/
