### ISSUE TITLE
Custom atlas

### ISSUE THREAD

**Issue by araikes** [PennBBL/qsiprep#134]
I know that we can use custom atlases. I have an atlas file that is a fusion of the Schaefer 400x17 atlas and Brainnetome's subcortical gray ROIs. 

Do you have any stock code for conforming it to the necessary orientation for QSIPrep's reconstruction? I know that I'd need to do the legwork on importing all of the ROI names.

**Comment by mattcieslak** [comment]
Have you seen [this section](https://qsiprep.readthedocs.io/en/latest/reconstruction.html#using-custom-atlases)?

**Comment by araikes** [comment]
I have. My image is RAS and doesn't have a zeroed out sform. I was just hoping you had ready-made code for making sure it was conformed so I didn't need to reinvent it.

I'll work on it.

**Comment by araikes** [comment]
Got it done and working.

**Comment by rtybanana** [comment]
Hi araikes,

Can you share details on how you got this to work? I'm in the same position as you and would like to use an atlas that's in RAS format.
