### ISSUE TITLE
how to input the freesurfer's license in the docker toolbox

### ISSUE THREAD

**Issue by longfangithub** [PennBBL/qsiprep#139]
The OS of my laptop is windows 10 enterprise, and has docker toolbox and virtualBox installed. Qsiprep is pulled with the docker toolbox.  The following problems arise: 
$ docker run -ti --rm -v /E_DRIVE/qsiprep_test/bidsdata:/data:ro -v /E_DRIVE/qsiprep_test/output:/out pennbbl/qsiprep:latest /data /out participant --output_resolution 3 --skip_bids_validation
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 507, in main
    set_freesurfer_license(opts)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 468, in set_freesurfer_license
    (for free) by registering at https://surfer.nmr.mgh.harvard.edu/registration.html""")
RuntimeError: ERROR: a valid license file is required for FreeSurfer to run. fMRIPrep looked for an existing license file at several paths, in this order: 1) command line argument ``--fs-license-file``; 2) ``$FS_LICENSE`` environment variable; and 3) the ``$FREESURFER_HOME/license.txt`` path. Get it (for free) by registering at https://surfer.nmr.mgh.harvard.edu/registration.html
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

How to place the Freesurfer license??

**Comment by araikes** [comment]
Mount it into the docker environment and either point QSIPrep to the file with the `--license_file` flag or just put it in the Freesurfer folder. For example:

```
docker run -ti --rm -v /E_DRIVE/qsiprep_test/bidsdata:/data:ro -v /E_DRIVE/qsiprep_test/output:/out -v /path/to/license.txt:/opt/freesurfer/license.txt pennbbl/qsiprep:latest /data /out participant --output_resolution 3 --skip_bids_validation
```

**Comment by mohammadrashid0917** [comment]
You could also consider using the qsiprep wrapper instead of directly using docker. You won't have to mount manually that way, the wrapper will handle it all for you
