### ISSUE TITLE
Is eddy interface missing in_mask input spec?

### ISSUE THREAD

**Issue by dPys** [PennBBL/qsiprep#14]
It looks like the mask variable is being passed correctly in https://github.com/PennBBL/qsiprep/blob/69d530ddf6573320609ab043e34135a904c5e167/qsiprep/workflows/dwi/fsl.py 

but I keep getting:

ValueError: ExtendedEddy requires a value for input 'in_mask'. For a list of required inputs, see ExtendedEddy.help()

Command:
```
qsiprep --bids_dir /data --output_dir /out/HNU1_output --analysis_level participant -w /tmp --output_resolution 2 --participant_label 0025427 --mem_mb 3200 --hmc-model eddy --eddy-config /root/eddy_params.json
```

where eddy_params.json consists of:
```
{
  "flm": "linear",
  "slm": "linear",
  "fep": false,
  "interp": "spline",
  "nvoxhp": 1000,
  "fudge_factor": 10,
  "dont_sep_offs_move": false,
  "dont_peas": true,
  "niter": 5,
  "method": "jac",
  "repol": true,
  "num_threads": 1,
  "is_shelled": false,
  "use_cuda": false,
  "cnr_maps": true,
  "residuals": true,
  "output_type": "NIFTI_GZ",
  "args": ""
}
```

Thoughts?

@dPys

FYI: have you played with eddy_quad yet? if so, what are your thoughts? doesn't seem to provide a ton of useful info beyond what other qc already offers, but it plays nice with the default eddy outputs.

**Comment by mattcieslak** [comment]
Could you update to 0.4.5? There was a bug where the mask wasn't being found if there was no distortion correction in earlier versions

**Comment by dPys** [comment]
Yep, that worked. 

Cheers,
@dPys
