### ISSUE TITLE
'pe_direction' trait of DiffusionSummaryInputSpec not being found

### ISSUE THREAD

**Issue by bwinsto2** [PennBBL/qsiprep#143]
Hi. First of all, thanks for making this app - we are excited to try it out in our lab.
We are running a simple pipeline on one subject using docker to test things out: 
<img width="421" alt="Screen Shot 2020-07-06 at 12 36 44 PM" src="https://user-images.githubusercontent.com/61159065/86617532-5bcdf000-bf85-11ea-8834-8d227955e58d.png">
Very soon after starting, we get this error:
<img width="681" alt="Screen Shot 2020-07-06 at 12 38 24 PM" src="https://user-images.githubusercontent.com/61159065/86617663-96d02380-bf85-11ea-8045-9b78c8779e03.png">
I'm wondering where qsiprep gets `pe_direction` from. In the JSON files that accompany my DWI files, I believe the Phase Encoding Direction is specific as 'j', but somehow it's getting an empty string: ' '. 
<img width="357" alt="Screen Shot 2020-07-06 at 12 40 12 PM" src="https://user-images.githubusercontent.com/61159065/86617811-d72fa180-bf85-11ea-855d-1f602ebac21c.png">
I tried working backwards a bit to check in the qsiprep code where DiffusionSummaryInputSpec comes from, but ultimately got a bit lost; any help would be appreciated. Thanks.

**Comment by mattcieslak** [comment]
Hi @bwinsto2, thanks for trying qsiprep! Does your input data pass BIDS validation? You need to have a `"PhaseEncodingDirection"` key in your JSON sidecar for this to work

**Comment by bwinsto2** [comment]
Thanks for your help on this. Yes, the data are BIDS compatible. Just did some research and looks like this is a known issue when converting DICOMs to NIfTIs with Philips data using dcm2niix. I should be able to figure it out and will update.
