### ISSUE TITLE
"Exception: No MNI to T1w transform found in anatomical directory" error during reconstruction workflows

### ISSUE THREAD

**Issue by mohammadrashid0917** [PennBBL/qsiprep#146]
I've successfully run the preprocessing workflow, and I'm now trying to run some of the reconstruction workflows. 

But, seemingly regardless of which workflow I run, I get this error  `"Exception: No MNI to T1w transform found in anatomical directory"`. (Fully detailed error message and crash report file is at the bottom)

Here is the full command I'm using:

    qsiprep-docker \
        /mohammad/testing/BIDS \
        /mohammad/testing/reconOutput \
        participant \
        -i pennbbl/qsiprep \
        --output-resolution 2 \
        --fs-license-file /mohammad/testing/license.txt \
        -w /mohammad/testing/intermediateWork \
        --recon_input /mohammad/testing/qsiprepOutput \
        --recon_spec mrtrix_multishell_msmt 

I've gotten this same error for all arguments I've put into the `--recon_spec` slot so far (though I haven't tried all of them)

I'm not sure of 1) which anatomical directory the error is referring to and 2) why there should be a MNI to T1w transform in it and where I would get said transform. The qsiprepOutput directory contains output from a successful run of just the qsiprep processing, so if this transform is something produced by qsiprep then I don't see why it  wouldn't be present.

Here is the error message I got in my terminal. 

	200715-15:29:57,293 nipype.workflow WARNING:
		 [Node] Error on "qsirecon_wf.sub-subjAC_mrtrix_multishell_msmt.recon_wf.get_atlases" (/scratch/qsirecon_wf/sub-subjAC_mrtrix_multishell_msmt/recon_wf/_dwi_file_..out..qsiprep..sub-subjAC..ses-AC1OCT202016Day1..dwi..sub-subjAC_ses-AC1OCT202016Day1_run-1_space-T1w_desc-preproc_dwi.nii.gz/get_atlases)
	200715-15:29:57,293 nipype.workflow ERROR:
		 Node get_atlases.a0 failed to run on host 494376fd3193.
	200715-15:29:57,295 nipype.workflow ERROR:
		 Saving crash info to /out/qsirecon/sub-subjAC/log/20200715-152942_8a37c84c-e8fb-4762-aebb-43372fa246c6/crash-20200715-152957-root-get_atlases.a0-1885df3c-b0b9-465a-81d3-92c227e08907.txt

The crash info file mentioned in the that error message is attached below. The final line of this crash file is what I put in the title.

[crash-20200715-152957-root-get_atlases.a0-1885df3c-b0b9-465a-81d3-92c227e08907.txt](https://github.com/PennBBL/qsiprep/files/4957637/crash-20200715-152957-root-get_atlases.a0-1885df3c-b0b9-465a-81d3-92c227e08907.txt)

Any help is much appreciated!

**Comment by mattcieslak** [comment]
Hi @mohammadrashid0917 to get the T1-to-MNI transform you need to add `--force-spatial-normalization` to your call to qsiprep during preprocessing. The next version will have this option enabled by default and the documentation needs to get updated (eg #117)

**Comment by mohammadrashid0917** [comment]
> 
> 
> Hi @mohammadrashid0917 to get the T1-to-MNI transform you need to add `--force-spatial-normalization` to your call to qsiprep during preprocessing. The next version will have this option enabled by default and the documentation needs to get updated (eg #117)

I will give that a shot, thank you very much!

**Comment by mohammadrashid0917** [comment]
Just to close off this issue: adding the --force-spatial-normalization flag to my call indeed fixed the "Exception: No MNI to T1w transform found in anatomical directory" error. Thanks again!

**Comment by tpatpa** [comment]
Hello,

I am using the qsiprep-docker wrapper version: 0.15.4.
I've successfully run the preprocessing for my data with the following command:

```
qsiprep-docker MY_PATH/data_experiment/ MY_PATH/data_experiment/derivatives/ \
participant --participant_label dMRI01 \
--fs-license-file MY_LICENSE_PATH/license.txt \
--work-dir MY_PATH/data_experiment/derivatives/temp_qsi \
--output-resolution 1.25 \
--hmc-model none \
--separate_all_dwis \
--output-space T1w \
--write-graph \
-vv
```

and now trying to run reconstruction ('mrtrix_singleshell_ss3t_noACT') with the following command:

```
qsiprep-docker MY_PATH/data_experiment/ MY_PATH/data_experiment/derivatives/ \
--recon_input MY_PATH/data_experiment/derivatives/qsiprep \
--recon_spec mrtrix_singleshell_ss3t_noACT \
--participant_label dMRI01 \
--separate_all_dwis \
--recon-only \
--fs-license-file MY_LICENSE_PATH/license.txt \
--work-dir MY_PATH/data_experiment/derivatives/temp_qsi \
--output-space T1w \
-vv
```
But received the following error:

```
Node: qsirecon_wf.sub-dMRI01_mrtrix_singleshell_ss3t_noACT.sub_dMRI01_ses_compact3T01_acq_diadem17iso_rec_none_dir_AP_run_01_space_T1w_desc_preproc_recon_wf.qsirecon_anat_wf.get_atlases
Working directory: /scratch/qsirecon_wf/sub-dMRI01_mrtrix_singleshell_ss3t_noACT/sub_dMRI01_ses_compact3T01_acq_diadem17iso_rec_none_dir_AP_run_01_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/get_atlases

Node inputs:

atlas_names = ['schaefer100x7', 'schaefer100x17', 'schaefer200x7', 'schaefer200x17', 'schaefer400x7', 'schaefer400x17', 'brainnetome246', 'aicha384', 'gordon333', 'aal116', 'power264']
forward_transform = <undefined>
reference_image = /qsiprep-output/sub-dMRI01/ses-compact3T01/dwi/sub-dMRI01_ses-compact3T01_acq-diadem17iso_rec-none_dir-AP_run-01_space-T1w_desc-preproc_dwi.nii.gz
space = T1w

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node get_atlases.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/utils.py", line 51, in _run_interface
    raise Exception("No MNI to T1w transform found in anatomical directory")
Exception: No MNI to T1w transform found in anatomical directory

```

The suggested fix here is to add --force-spatial-normalization to qsiprep during preprocessing but this was later deprecate and made the default (hence I get `qsiprep: error: unrecognized arguments: --force-spatial-normalization`)


Any thoughts are very much welcomed!
