### ISSUE TITLE
Prepackaged Recon Spec Starting Incorrect Workflow

### ISSUE THREAD

**Issue by smeisler** [PennBBL/qsiprep#147]
Hello,

I just started using QSIPrep (0.9.0beta1) yesterday; I am very excited by the notion of a fully automated and reproducible pipeline, so thank you for your continued efforts in developing this!

I am testing on two subjects with single-shelled (b=1000) acquisition and no reverse PE b0 image available (so I cannot do SDC). Since the program I use for tractography, TractSeg, expects peaks exported from MrTrix, this seems to leave me with one recon option, which is **mrtrix_singleshell_ss3t_noACT**. I run qsiprep with the singularity command: 

`singularity exec -B /DATA --nv -e  /PATH/TO/qsiprep.img \`
`qsiprep /PATH/TO/BIDS \`
`/PATH/TO/DERIVATIVES \`
`participant \`
`-w /PATH/TO/DERIVATIVES \`
`--output-resolution 1 --hmc_model eddy \`
`--recon-spec mrtrix_singleshell_ss3t_noACT --fs-license-file /PATH/TO/license.txt  \`
`--unringing_method mrdegibbs --force-spatial-normalization`

However, when reconstruction starts, I see the following message: 

> [Node] Setting-up "qsirecon_wf.sub-reader001_mrtrix_**multishell**_msmt_noACTmsmt.recon_wf.qsiprep_preprocessed_dwi_data" in "/om2/vast/gablab/smeisler/qsiprep_testing/derivatives/qsirecon_wf/sub-reader001_mrtrix_**multishell**_msmt_noACTmsmt/recon_wf/_dwi_file_..om2..vast..gablab..smeisler..qsiprep_testing..derivatives..qsiprep..sub-reader001..ses-pre..dwi..sub-reader001_ses-pre_run-1_space-T1w_desc-preproc_dwi.nii.gz/qsiprep_preprocessed_dwi_data".

So it appears that it is starting the multishell workflow. Of note, the recon description text that proceeds the processing does correctly describe the MrTrix3Tissue single shell protocol.

Also, why does ACT require SDC? I thought only having the 5tt T1 (and multishell acquisition, but dhollander seems to suffice for single-shell) was sufficient for ACT.

Thanks again for your help,
Steven

**Comment by mattcieslak** [comment]
The pipeline is correct, it just has the wrong workflow name in the json file. This will be fixed soon #150

**Comment by smeisler** [comment]
Got it, thanks! I'll close this issue since you opened the fix request. Also, incase anyone was curious about the last question I posed regarding why ACT requires SDC, it is answered here: https://community.mrtrix.org/t/act-and-no-reversed-phase-encoding-information/1122
