### ISSUE TITLE
DWI Preprocess Not Outputting MNI Files

### ISSUE THREAD

**Issue by smeisler** [PennBBL/qsiprep#148]
Hello,

I am running qsiprep (0.9.0beta1) through singularity with the following command:
`singularity exec -B /DATA --nv -e /PATH/TO/qsiprep.img \`
`qsiprep /PATH/TO/BIDS \`
`/PATH/TO/DERIVATIVES \`
`participant \`
`-w /PATH/TO/DERIVATIVES \`
`--output-resolution 1 --hmc_model eddy \`
`--recon-spec mrtrix_singleshell_ss3t_noACT --fs-license-file /PATH/TO/license.txt \`
`--unringing_method mrdegibbs --force-spatial-normalization`

Looking in my qsiprep output folder, I can easily find the MNI outputs for the anatomy preprocessing. However, the DWI preprocessing outputs are only in subject T1 space. Based on what I read at https://qsiprep.readthedocs.io/en/latest/preprocessing.html, it seems like it should be possible to output into MNI space as well, even if the "template" argument for --output-space is deprecated. This would be ideal, since for my tractography and tractometry analysis, I would like to start with CSD peaks from reconstruction in a standard space.

In the case that qsiprep cannot output these files directly, I see that in the qsiprep/subXXX/anat folder there are some xfm.hd5 files that I presume can be used to transform the DWI to MNI space (assuming the DWI was first registered to the T1). Do you know what kind of program would use a .hd5 for this purpose? I usually use FSL flirt which could take a .txt or .mat matrix to inform the transformation.

Thanks for the assistance,
Steven

**Comment by mattcieslak** [comment]
Hi Steven,

Thanks for trying QSIPrep. The preprocessing pipeline does not write outputs to MNI space because the preprocessing registration only uses the T1w image. I'm going to update the commandline args and documentation to better reflect this #149.
