### ISSUE TITLE
[BUG] "ValueError: operands could not be broadcast together with shapes (135,) (199,)" during qsiprep

### ISSUE THREAD

**Issue by dseok** [PennBBL/qsiprep#154]
qsiprep fails during preprocessing due to value error.

qsiprep version: 0.9.0beta1

Call:

    singularity run --cleanenv -B ${data_root}:/data --nv ${img} \
    ${niidir} ${outdir} participant --work-dir ${workdir} \
    --participant-label ${sub} --skip_bids_validation \
    --low-mem --mem-mb 47000 --nthreads 1 --omp-nthreads 1 \
    --distortion-group-merge average --combine-all-dwis \
    --output-resolution 1.5 --force-spatial-normalization \
    --eddy-config eddy_params.json \
    --fs-license-file ${fs_license}

eddy_params.json:
`{ "flm": "linear", "slm": "linear", "fep": false, "interp": "spline", "nvoxhp": 1000, "fudge_factor": 10, "dont_sep_offs_move": false, "dont_peas": false, "niter": 5, "method": "jac", "repol": true, "num_threads": 1, "is_shelled": true, "use_cuda": true, "cnr_maps": true, "residuals": false, "output_type": "NIFTI_GZ", "args": "" }`

[crash-20200728-122829-anxiousmisery-distortion_merger-8b38500e-d99c-4467-8b5f-166203ea5005.txt](https://github.com/PennBBL/qsiprep/files/4996269/crash-20200728-122829-anxiousmisery-distortion_merger-8b38500e-d99c-4467-8b5f-166203ea5005.txt)

[qsiprep_sub-NDARPK532CVC_8193119.o.txt](https://github.com/PennBBL/qsiprep/files/4996270/qsiprep_sub-NDARPK532CVC_8193119.o.txt)

**Comment by dseok** [comment]
This participant had their DWI sequences interrupted twice. All of our participants have two pairs (opposite PE) of dir-98 and two pairs of dir-99, with 99 and 100 volume acquisitions, respectively. This participant had both of their PA scans interrupted (dir-98 had 96/99 volumes and dir-99 had 39/100 volumes).

**Comment by mattcieslak** [comment]
Based on the error message, it seems like the interrupted scans are preventing the distortion group merge from working. For the HCP-style merging you need to have scans with matching bvals/bvecs in both directions. This subject might not be usable
