### ISSUE TITLE
Using qsiprep with Phillips scanner

### ISSUE THREAD

**Issue by unimusic** [PennBBL/qsiprep#157]
I am trying to use qsiprep with images in BIDS format, but taken with a Phillips scanner. This means that the phase encoding direction is not available, because Phillips machines currently don't store this information as metadata. Is it still possible to use qsiprep with these images? The names of the scans do usually say that they are 'Axial'. If we assume Axial scans are L to R, Does this tell us what the phase encoding direction is? What letter would represent this?

Thank you!

Angela

**Comment by mattcieslak** [comment]
Hi Angela, Are you planning on using TOPUP for these? Or do you have GRE fieldmaps? If topup, you can make an arbitrary choice as long as you know ahead of time which image is which direction

**Comment by unimusic** [comment]
I'm using TOPUP I think. From this [link](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/topup/Faq), It is the first image and the second image (one of each). What do you mean by which image is which direction? Thanks.

**Comment by mattcieslak** [comment]
Were you able to sort this out? I meant which group corresponds to + and which to -.

**Comment by mattcieslak** [comment]
Closing for now, please reopen if you are still having issues
