### ISSUE TITLE
[ENH] Add a utility for aggregating QA metrics on a cohort

### ISSUE THREAD

**Issue by mattcieslak** [PennBBL/qsiprep#163]
Idea
-----

Make an entrypoint called something like `qsiprep-aggregate` that grabs QC data from the qsiprep outputs from a study and creates a CSV and/or json that can be loaded in a dmriprep-viewer-style app.

**Comment by richford** [comment]
Could this just be what happens by default when you change the usual BIDS-App `participant` parameter to `group`.

**Comment by mattcieslak** [comment]
So add it to the sidecar in the derivatives? I like this idea

**Comment by mattcieslak** [comment]
I think in the long run we might save `group` for building an FOD template or something like that. I'm thinking we might be able to add some of the info into json sidecars that come out of the `participant` pipeline though, so you don't have to run an extra utility
