### ISSUE TITLE
[BUG]: ImportError: cannot import name 'NUMPY_MMAP' from 'nipype.utils'

### ISSUE THREAD

**Issue by FL33TW00D** [PennBBL/qsiprep#172]
Hi there,
I am using QSIPrep v0.11.0 through the singularity container using the following command:

`singularity run --cleanenv --bind /gpfs/home/vhe17qgu/qsiprep:/qsiprep qsiprep-0.11.0.sif \
    qsiprep_test_data \
    output_dir \
    participant \
    --work-dir working_dir \
    --fs-license-file license.txt \
    --nthreads 8 --unringing-method mrdegibbs \
    --hmc-model 3dSHORE \
    --prefer-dedicated-fmaps \
    --output-resolution 1
`

I am receiving the following error: 
ImportError: cannot import name 'NUMPY_MMAP' from 'nipype.utils'

It seems like this is due to an outdated import according to the Nipype repo? It's a brand new image so not sure why this would happen since the issue was resolved in May 2017 at the following ticket: [#1898](https://github.com/nipy/nipype/issues/1898)

EDIT:
I pulled the QSIPrep repo and looked through the code, just looks like a change from

`from nipype.utils import NUMPY_MMAP -> from nipype.utils.config import NUMPY_MMAP`

will do the job. unfortunately I am unaware of how to edit the code and then rebuild it into a Singularity Container.

Please let me know your thoughts.

Many Thanks,
Chris

**Comment by fredrmag** [comment]
I think this is due to nipype 1.5.0 has taken away the NUMPY_MMAP altogether: https://github.com/nipy/nipype/pull/3121

**Comment by FL33TW00D** [comment]
> I think this is due to nipype 1.5.0 has taken away the NUMPY_MMAP altogether: [nipy/nipype#3121](https://github.com/nipy/nipype/pull/3121)

Ah that does seem to be the case.
I am unsure of the solution here then, waiting for @mattcieslak to hopefully guide me.

Thanks for the reply.

**Comment by fredrmag** [comment]
I believe that the solution to this, is to: 
1. remove all `from nipype.utils import NUMPY_MMAP` lines in the code. 
2. change all `nb.load` commands from `nii = nb.load(volume, mmap=NUMPY_MMAP)` to `nii = nb.load(volume)`

**Comment by fredrmag** [comment]
Seems to only be in one file:
https://github.com/PennBBL/qsiprep/blob/e1f7db9ff4a393fdd0748f52451e91d20008ccb5/qsiprep/workflows/fieldmap/utils.py#L53-L66

**Comment by fredrmag** [comment]
I have opened a PR (#174) to try to fix it.

**Comment by FL33TW00D** [comment]
@fredrmag Thank you so much for fixing this.
