### ISSUE TITLE
Read in and use h5 files for spatial transformation

### ISSUE THREAD

**Issue by SendyCaffarra** [PennBBL/qsiprep#183]
Hi,

I'm trying to perform a spatial transformation using the h5 files from the qsi-prep output but I keep getting errors that seem to be related to the format of these files (here below an example). How can I load and read the h5 file properly? Thanks! Sendy

<img width="1250" alt="Screen Shot 2020-09-22 at 4 57 11 PM" src="https://user-images.githubusercontent.com/64933137/93953387-28873b80-fd00-11ea-9cdd-92da735419e1.png">

**Comment by mattcieslak** [comment]
Hi! I'm not familiar with nitransforms, the h5 files from QSIPrep are ANTs/ITK transforms from a relatively recent version of ANTs. You can use these with the `antsApplyTransforms` program included in the docker image, or compile a recent ANTs to do this locally. If you'd like to stick with python, you can use [antspy](https://github.com/ANTsX/ANTsPy)

**Comment by mattcieslak** [comment]
Please reopen if you're still having trouble working with the h5 files!

**Comment by SendyCaffarra** [comment]
I am currently trying to run Ants from the qsiprep docker but cannot figure out the right syntax. How can I get an Ants command running within the qsiprep image? Here is what I tried:  docker run --rm -it -v /mnt/ROIs/opticchiasm.nii:/ROI/roi.nii:ro -v /mnt/sub-NLR160EK_desc-preproc_T1w.nii.gz:/reference/T1.nii.gz:ro -v /mnt/output/Op_chiasm.nii.gz:/out/MNI_roi.nii.gz -v /mnt/qsiprep/sub-NLR160EK/anat/sub-NLR160EK_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5:/trans/trans.h5 pennbbl/qsiprep:0.11.5 antsApplyTransforms -i /ROI/roi.nii / -r /reference/T1.nii.gz -o /out/MNI_roi.nii.gz -t /trans/trans.h5
