### ISSUE TITLE
gradients flipped when processing GE data

### ISSUE THREAD

**Issue by jyeatman** [PennBBL/qsiprep#194]
When we process data from a GE scanner the qsi-prep output seems to have flipped FODs. DICOM-> nifti conversion was done through flywheel which uses dcm2nii. Is this a known issue and does it have a simple fix? Has anyone processed GE data with qsi-prep yet? If not, I'm happy to upload the problematic dataset
![sub-001_ses-1_acq-g81_run-1_space-T1w_desc-preproc_space-T1w_desc-wmFOD_odfs](https://user-images.githubusercontent.com/1775818/99111048-40f93100-25a0-11eb-8d5a-f0a65feedaed.png)

**Comment by mattcieslak** [comment]
Thanks for reporting this! We test on GE data from ABCD, so far we haven't encountered this. Which reconstruction workflow is this from? And do the bvecs work with other software?

**Comment by jyeatman** [comment]
This is the mrtrix_multishell_msmt workflow. We have preprocessed the data using [dtiInit from vistasoft](https://github.com/vistalab/vistasoft/blob/master/mrDiffusion/dtiInit/dtiInit.m) using the [rotateBvecsWithCanlXform flag](https://github.com/vistalab/vistasoft/blob/441388330d1f8ca32c8f6f69b5977aafd69fa9b8/mrDiffusion/dtiInit/dtiInitParams.m#L85) and it runs fine. I have heard others report that for mrtrix the bvecs need to be flipped over the x or y axis (but I haven't yet tested this myself. Do you want us to post a dataset online?

**Comment by mattcieslak** [comment]
The mrtrix reconstruction workflows use the `.b` gradient table file, not the bvecs. This whole setup is confusing and undocumented, thanks for your patience. There are a couple things that could fix this in the short term

 - You could manually flip the directions in the `.b` file before running the recon workflows
 - You can run `dwigradcheck` on the bvecs to get a correctly-oriented mrtrix gradient table

In the longer term I'd like to make an option for all the reconstruction workflows to run `dwigradcheck`. There is a lot of preprocessed data out there that would be nice to not need to reprocess.

**Comment by jyeatman** [comment]
Thanks Matt. We'll try that on our data and then post the results to document how these various factors interact for GE (hyperband) data.

**Comment by jyeatman** [comment]
Okay, so I still don't fully understand what was going on here but it appears to be an interaction between GE <-> dcm2nii <->qsi-prep. The way that the gradients were being extracted worked with some software packages but not qsi-prep. But there was a recent update to dcm2nii and now all these issues have gone away. The image below shows the same data but with niftis created using the release of dcm2nii from last month.
![image (2)](https://user-images.githubusercontent.com/1775818/101068538-b2981f80-354d-11eb-9816-375c3dc2b5c0.png)
