### ISSUE TITLE
BIDS: sometimes recognizes fmap files

### ISSUE THREAD

**Issue by andyrevell** [PennBBL/qsiprep#208]
Hey thanks for making this - also at Penn here.
For some reason, running qsiprep will grab the fieldmap files, and sometimes it will not, despite two subjects having the exact same folder structures and acquisitions. For example in the screenshots below, sub-RID0278 properly runs, but RID0213 does not. I cannot pinpoint what the issue is.

![image](https://user-images.githubusercontent.com/43831513/103304425-9e253680-49d6-11eb-87eb-b84ba0d6e636.png)

![image](https://user-images.githubusercontent.com/43831513/103304444-a9786200-49d6-11eb-81bf-aec168b2153a.png)

![image](https://user-images.githubusercontent.com/43831513/103304452-af6e4300-49d6-11eb-9d3f-4521f68963ee.png)
![image](https://user-images.githubusercontent.com/43831513/103304459-b5642400-49d6-11eb-8ce0-62bdf70a8cf6.png)

**Comment by mattcieslak** [comment]
Hi Andy, do both phasediff files have "IntendedFor" in their json sidecars?

**Comment by andyrevell** [comment]
Great that seems to work! I added the "IntendedFor" in the json files. You may close this issue. 

Screenshot below for others having the same issue. We had two people convert the dicoms using dcm2niix, and must have done it differently where the json files were not created equally. 
![image](https://user-images.githubusercontent.com/43831513/103308163-c9605380-49df-11eb-83a0-ff8700675a36.png)

**Comment by mattcieslak** [comment]
Unfortunately dcm2niix doesn't fill out this particular field, so it's up to whoever performs bids curation to add these. Glad this worked!
