### ISSUE TITLE
dtifit directions possibly affected by missing sform orientation information?

### ISSUE THREAD

**Issue by ethanknights** [PennBBL/qsiprep#218]
Hi 
We've tried using qsiprep output (i.e. the dti data, mask, bvecs, bvals) as input to FSL's `dtifit` for a few subjects but noticed the resulting directions seem off (pic attached below of a V1 & FA modulated image, over corpus callosum).

One thought is whether this could be related to the sform fields not being preserved in the .nii headers for qsiprep output e.g. for qsiprep output (but not the raw images):
`sform_code = 0` 
`sform_?orient = Unknown`
etc. 

We will try updating this orientation info manually next (e.g. https://nipy.org/nibabel/nifti_images.html)  but wanted to ask if there were any thoughts on what could cause this please (e.g. sform related or not)?

Another thing we checked was the phase encoding direction, but we don't think that caused this (i.e.  `-j ` was in the .html reports). 

Maybe this issue is related? #186
For our qsiprep singularity command, see the end of original post in #193 

thanks
Ethan @fredrmag @WilliamFCB

![tmp Image DWI](https://user-images.githubusercontent.com/34215814/105845428-9c995f00-5fd2-11eb-8c0c-f182ac62201a.png)

**Comment by mattcieslak** [comment]
Hi! I think this is actually due to differences in how FSL interprets bvecs. Could you try flipping the y direction in the bvecs and running this workflow? Also, is there a standard workflow with FSL that would be worth adding an official reconstruction workflow to qsiprep? If so we can add the y-flip to the workflow so users won't have to do this manually.

**Comment by araikes** [comment]
Hi @mattcieslak 

1. I can confirm that this is the case with the directions when using DTIFIT
2. The most "standard" workflow for using FSL is here (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FDT/UserGuide) at least up through BEDPOSTX.
3. See https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FDT/FAQ#What_conventions_do_the_bvecs_use.3F for BVEC convention for FSL

**Comment by mattcieslak** [comment]
@araikes it looks like this is a pretty simple workflow. The main reason I've been reluctant to add an FDT reconstruction workflow is that qsiprep was made to showcase more advanced methods and make them easily accessible. For example the single shell 3-tissue workflow is outstanding and has a nice probabilistic tractography run at the end. Practically, though, it is somewhat common to have a reviewer ask for a comparison to FDT.

**Comment by araikes** [comment]
Also, and for good measure this requires an x flip and can be really easily fixed for use with FDT (just checked) using MRtrix's `dwigradcheck`. E.g. (from a QSIPrep folder)

```
dwigradcheck -i ..preproc_dwi.nii.gz -m ...brain_mask.nii.gz -fslgrad ...preproc_dwi.bvec ...preprov_dwi.bval -export_grad_fsl ...rotated.bvec ...rotated.bval

dtifit -k ...preproc_dwi.nii.gz -m ...brain_mask.nii.gz -r ...rotated.bvec -b ...rotated.bval
```

![image](https://user-images.githubusercontent.com/18663624/105879996-0fe5a580-5fc0-11eb-91b3-26bef8834e5b.png)

**Comment by ethanknights** [comment]
Thanks both for your fast and clear responses! 
I just tried flipping the y values in the .bvec file and rerunning `dtifit`, but I didn't see any change (the image below shows the original map (left) and the new map with rotated y values (right)).

I think I performed the y flip correctly - I simply rewrote the .bvec file after flipping the sign of the second row's values using matlab (e.g. `b(2,:) = -b(2,:);  %%%% where b is 3 [x,y,z] x 63 [volumes] array`).

(Unfortunately I couldn't try performing the flip with `dwigradcheck` -  mrtrix3 isn't installed right now on this cluster (will look into that), and I can't export data from the cluster currently either, so I can't try using my laptop's mrtrix installation). 

Will have another try after flipping the x axis as @araikes suggested.

![Screenshot 2021-01-26 at 22 28 39](https://user-images.githubusercontent.com/34215814/105914364-29b9d380-6026-11eb-981e-418b01ba945a.png)

**Comment by araikes** [comment]
You can use `dwigradcheck` using QSIPrep :)

```
singularity exec /path/to/qsiprep.sif dwigradcheck -i .....
```

**Comment by ethanknights** [comment]
D'oh - of course! Will report back

**Comment by ethanknights** [comment]
Thanks @mattcieslak @araikes this indeed seems to have worked! - `dwigradcheck` produced an x-flipped .bvec, which looked closer to what we'd have expected with fsleyes.

(Will be interested to see whether this less advanced reconstruction pipeline is added to qsiprep in the future - I understand both points of view!) 

Will close the issue.
