### ISSUE TITLE
Recon workflow: Exception: Unable to find subject directory in..

### ISSUE THREAD

**Issue by IRuotsa** [PennBBL/qsiprep#226]
Hi!
I'm testing the recon workflow with following command:  
`singularity run --cleanenv /usr/local/qsiprep/qsiprep-0.13.0RC1.sif  --recon-only --recon_input path/to/bids/folder/derivatives/qsiprep --recon_spec mrtrix_singleshell_ss3t --fs-license-file path/to/bids/folder/sourcedata/license.txt path/to/bids/folder/ path/to/bids/folder/derivatives/qsiprep_recon participant`

However, I get following error message:
```
210209-12:58:47,36 nipype.workflow INFO:
	 sub-001 not in path/to/bids/path/to/bids/folder/derivatives/qsiprep, trying recon_input=/path/to/bids/path/to/bids/folder/derivatives/qsiprep/qsiprep
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 1114, in build_recon_workflow
    sloppy=opts.sloppy
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/recon/base.py", line 95, in init_qsirecon_wf
    sloppy=sloppy
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/recon/base.py", line 159, in init_single_subject_wf
    recon_input, qp_recon_input))
Exception: Unable to find subject directory in path/to/bids/path/to/bids/folder/derivatives/qsiprep or path/to/bids/path/to/bids/folder/derivatives/qsiprep/qsiprep
```
It appears that path to subject is wrong (`path/to/bids/path/to/bids/folder/derivatives/qsiprep`), even though it's written correctly in the code (`path/to/bids/folder/derivatives/qsiprep`).

Do you know what's happening here?
Thanks!

**Comment by FL33TW00D** [comment]
Hi @IRuotsa ,
Is this the command you are running verbatim? 
```
singularity run --cleanenv /usr/local/qsiprep/qsiprep-0.13.0RC1.sif --recon-only --recon_input path/to/bids/folder/derivatives/qsiprep --recon_spec mrtrix_singleshell_ss3t --fs-license-file path/to/bids/folder/sourcedata/license.txt path/to/bids/folder/ path/to/bids/folder/derivatives/qsiprep_recon participant
```

If so, you should be changing the path to the actual location of your files in your file system. ie (home/data/sub-001)

Hope this helps!

**Comment by IRuotsa** [comment]
Hi @FL33TW00D and thank you for getting back to me! I managed to get it running when moving the `/path/to/bids/folder /path/to/bids/folder/derivatives/qsiprep_recon participant` to the beginning of the command (after singularity image) as in the example. Also there was one missing "/" before home-folder in the command.

**Comment by akelkar26** [comment]
Hi,
I am running into the same issue of the recon-input not finding the subject directory even though it exists on that path.

I am running the following command for TNI05P :
docker run -ti \
    -v /Users/neurouser1/Documents/TNI_Stroke/bids_directory/:/data \
    -v /Users/neurouser1/Documents/TNI_Stroke/qsiprep_dsistudiorecononly/:/out \
    -v /Users/neurouser1/Documents/fs_files/:/license \
    -v /Users/neurouser1/Documents/TNI_Stroke/scratch/:/scratch \
    pennbbl/qsiprep:latest \
    /data /out participant \
    --participant_label sub-TNI05P \
    --recon_input /Users/neurouser1/Documents/TNI_Stroke/qsiprepout_dwionly/qsiprep \
    --recon_only \
    --recon_spec dsi_studio_gqi \
    --fs-license-file /license/license.txt \
    -w /scratch/ \
    --output-resolution 1.3 \
    --n_cpus ‘15’ \
    --omp-nthreads 8 \
    --mem_mb 150000 \
    
    My output is:
    210603-20:41:15,503 nipype.workflow IMPORTANT:

    Running qsirecon version 0.13.0RC1:
      * BIDS dataset path: /data.
      * Participant list: ['TNI05P'].
      * Run identifier: 20210603-204113_f61a4cb8-6452-49ee-a271-e8ec4d0affd5.

210603-20:41:15,504 nipype.workflow INFO:
         sub-TNI05P not in /Users/neurouser1/Documents/TNI_Stroke/qsiprepout_dwionly/qsiprep, trying recon_input=/Users/neurouser1/Documents/TNI_Stroke/qsiprepout_dwionly/qsiprep/qsiprep
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 1114, in build_recon_workflow
    sloppy=opts.sloppy
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/recon/base.py", line 95, in init_qsirecon_wf
    sloppy=sloppy
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/recon/base.py", line 159, in init_single_subject_wf
    recon_input, qp_recon_input))
Exception: Unable to find subject directory in /Users/neurouser1/Documents/TNI_Stroke/qsiprepout_dwionly/qsiprep or /Users/neurouser1/Documents/TNI_Stroke/qsiprepout_dwionly/qsiprep/qsiprep


Am I giving a wrong input?
Thanks in advance for the help.

**Comment by rtybanana** [comment]
Hi @akelkar26,

The error message is telling you that it can't find the qsiprep output which you supply with the `--recon_input` switch in the qsiprep command. The reason it can't find this folder is because the docker instance has no default knowledge of your documents tree. In order to access any of your files you need to map the location to the mounted docker instance. You have done this for some of your other paths using the `-v` switch in the docker command.

```
-v /Users/neurouser1/Documents/TNI_Stroke/bids_directory/:/data
-v /Users/neurouser1/Documents/TNI_Stroke/qsiprep_dsistudiorecononly/:/out
-v /Users/neurouser1/Documents/fs_files/:/license
-v /Users/neurouser1/Documents/TNI_Stroke/scratch/:/scratch 
```

To fix this you should map your recon input location` /Users/neurouser1/Documents/TNI_Stroke/qsiprepout_dwionly/qsiprep` to a mounted location of your choice, such as:

```
-v /Users/neurouser1/Documents/TNI_Stroke/qsiprepout_dwionly/qsiprep/:/recon_input
```

And then use this mounted location in the `--recon_input` switch.

```
docker run -ti
    -v /Users/neurouser1/Documents/TNI_Stroke/bids_directory/:/data
    -v /Users/neurouser1/Documents/TNI_Stroke/qsiprep_dsistudiorecononly/:/out
    -v /Users/neurouser1/Documents/fs_files/:/license
    -v /Users/neurouser1/Documents/TNI_Stroke/scratch/:/scratch
    -v /Users/neurouser1/Documents/TNI_Stroke/qsiprepout_dwionly/qsiprep/:/recon_input
    pennbbl/qsiprep:latest
        /data /out participant
        --participant_label sub-TNI05P
        --recon_input /recon_input
        --recon_only
        --recon_spec dsi_studio_gqi
        --fs-license-file /license/license.txt
        -w /scratch/
        --output-resolution 1.3
        --n_cpus ‘15’
        --omp-nthreads 8
        --mem_mb 150000 \
```

Hope this helps you to diagnose these problems in future!

**Comment by akelkar26** [comment]
Hi @rtybanana thank you so much for the detailed explanation. I should have realized I needed to mount the recon input as well. This was good learning for me. I tested it and it worked well. 
Thank you for all the help. I will remember to see if I have mounted all inputs when using docker in the future.
