### ISSUE TITLE
No evidence that syn-sdc was run

### ISSUE THREAD

**Issue by smeisler** [PennBBL/qsiprep#231]
Hi,

### QSIPrep version
0.13.RC1
### Installation
Singularity on Linux HPC
### Command
`singularity run -B ${scratch}:/workdir -B ${bids_dir}:/mnt:ro -B ${output_dir}:/output -B ${bids_dir}/code/qsiprep/license.txt:/license.txt $IMG --participant_label ${subject:4} -w /workdir --fs-license-file /license.txt --mem_mb 20000 --use-syn-sdc --unringing_method mrdegibbs --skip-bids-validation --output_resolution 1.2 /mnt /output participant
`
### Error
No error, but the boilerplate does not mention syn-sdc, nor do I see any workflow initiated with "syn-sdc" in the slurm outfiles
### Notes
1 DWI file (30 directions at b=1000, 4 baseline at b=0) with T1w

Cache was cleared before running

QSIPrep runs to completion

fMRIPrep did run syn-sdc successfully

**Comment by mattcieslak** [comment]
Could you try running with `--force-syn`? I think there's a bug in handling the arguments.

**Comment by smeisler** [comment]
Thanks, I'll give it a shot. Should that be used in addition to `--use-syn-sdc`, or does it make a difference?

**Comment by mattcieslak** [comment]
The CI test that runs SyN [uses both](https://github.com/PennBBL/qsiprep/blob/master/.circleci/config.yml#L353), but I think `--force-syn` will do it

**Comment by smeisler** [comment]
That worked, closing the issue.
