### ISSUE TITLE
[BUG] N4BiasFieldCorrection: Inputs do not occupy the same physical space!

### ISSUE THREAD

**Issue by xiaosonghe** [PennBBL/qsiprep#24]
During early step when b0 image will be corrected for bias field, sometimes probably due to some precision issue that some dimension parameters of the b0 image and its corresponding mask are not considered as matched (could not pass the tolerance test of 10^6, some suggest to lower the tolerance to 10^2 to solve this problem). A possible solution is to omit the mask during this process.

Example script where error emerges:
N4BiasFieldCorrection -d 3 --input-image /data/qsiprep_wf/single_subject_XXX_wf/dwi_preproc_wf/hmc_sdc_wf/sdc_wf/pepolar_unwarp_wf/prepare_epi_opposite_wf/split/mapflow/_split0/vol0000.nii.gz --mask-image /data/qsiprep_wf/single_subject_XXX_wf/dwi_preproc_wf/hmc_sdc_wf/sdc_wf/pepolar_unwarp_wf/prepare_epi_opposite_wf/enhance_and_skullstrip_dwi_wf/initial_mask/vol0000_mask.nii.gz --output vol0000_corrected.nii.gz

Example suggestion:
N4BiasFieldCorrection -d 3 --input-image /data/qsiprep_wf/single_subject_XXX_wf/dwi_preproc_wf/hmc_sdc_wf/sdc_wf/pepolar_unwarp_wf/prepare_epi_opposite_wf/split/mapflow/_split0/vol0000.nii.gz --output vol0000_corrected.nii.gz

**Comment by cookpa** [comment]
Do you have example data, or at least error output that shows it's a precision issue? It's possible but I would not assume that.

**Comment by xiaosonghe** [comment]
Yes! Actually I've been discussing with Matt and it was him who suggested me to post it here. The funny thing is the error log exported from qsiprep actually did not gave any details, according to Matt whom I sent two copies of error log. Then I tested the same data both inside and outside the container, and only with the --verbose could I see the error:

Running N4 for 3-dimensional images.

Exception caught: 
itk::ExceptionObject (0x24331b0)
Location: "unknown" 
File: /fmriNASTest/data00/tools/antsbin/ITKv4-install/include/ITK-4.12/itkImageToImageFilter.hxx
Line: 241
Description: itk::ERROR: N4BiasFieldCorrectionImageFilter(0x242a0b0): Inputs do not occupy the same physical space! 
InputImage Origin: [-1.2549351e+02, 7.8891526e+01, -6.2374967e+01], InputImage_1 Origin: [-1.2549347e+02, 7.8891524e+01, -6.2374999e+01]
	Tolerance: 6.8571429e-06
InputImage Direction: 9.9671284e-01 8.0192861e-02 1.1516290e-02
7.5650495e-02 -9.7212552e-01 2.2192111e-01
-2.8991768e-02 2.2032041e-01 9.7499661e-01
, InputImage_1 Direction: 9.9671260e-01 8.0194147e-02 1.1527811e-02
7.5649198e-02 -9.7212552e-01 2.2192155e-01
-2.9003287e-02 2.2031994e-01 9.7499638e-01

	Tolerance: 1.0000000e-06

Yes, I found online one of the strategy is to change the tolerance to a higher value such as 10^2. However this step is automatically generated and executed in qsiprep so as the enduser I can not feed such specific parameter for such specific step. That's why it needs to be mitigated from the beginning but not during using qsiprep.

**Comment by cookpa** [comment]
OK. Unfortunately a decision was made some time ago to suppress most error output in ANTs without `--verbose`. 

I think changing the tolerance might need to be done at compile time. 

There was also a bug some time ago where a sufficient number of multi-resolution levels could cause this, but I think that was fixed in ITK. If you have the verbose output, you can tell if the error happened at the beginning of the call to N4 (likely headers being off) or after it has run for some time.

**Comment by mattcieslak** [comment]
This is a qsiprep issue, ANTs correctly noticed that the mask and image aren't in the correct space. I'm going to fix this by not using a mask, since it was a bad mask anyways. Also maybe I should turn on verbose for all ANTs commands?

**Comment by cookpa** [comment]
Verbose is good, if annoying to scroll through.

I'm not sure how much impact the mask has on bias correction. Reading the Sled paper, it seems he was mostly doing it for performance reasons. In N4, the bias field is not applied outside of the brain mask, so if you don't trust the mask it might be better to not use it.

**Comment by xiaosonghe** [comment]
Do you think the mask should be ignored for all N4 just in case for T1 image somehow it causes trouble again?

**Comment by mattcieslak** [comment]
I'm only planning on removing it from this specific part of the pipeline (which deals with b=0 images).

**Comment by xiaosonghe** [comment]
No problem! I will test and let you know and hopefully it will be OK for the whole pipeline.
