### ISSUE TITLE
[ENH] syn-sdc ignored in the report for 3dSHORE pipeline and omitted in eddy pipeline

### ISSUE THREAD

**Issue by xiaosonghe** [PennBBL/qsiprep#26]
For distortion correction, the sun-sdc pipeline got ignored, even when both --use-syn-sdc and --force-syn flags are on. This bug stays regardless whether the fieldmaps are ignored or not. [tested by Matt and Xiaosong]

**Comment by mattcieslak** [comment]
Here is the test where it's not writing the report to the html: https://955-156589095-gh.circle-artifacts.com/0/tmp/DSCSDSI/derivatives/qsiprep/sub-tester.html

It is actually running syn, just not writing a report. Here is the unwarped file from testing: https://955-156589095-gh.circle-artifacts.com/0/tmp/DSCSDSI/work/qsiprep_wf/single_subject_tester_wf/dwi_preproc_acq_HASC55AP_wf/hmc_sdc_wf/sdc_wf/syn_sdc_wf/unwarp_ref/average_trans_TruncateImageIntensity_RescaleImage_corrected_Sharpen_trans.nii

**Comment by xiaosonghe** [comment]
I would recommend to change this relative minor issue as an enhancement suggestion: (1) having the report accurately document the syn-sdc process for 3dshore pipeline; (2) implement syn-sdc after eddy for eddy pipeline (currently omitted in eddy pipeline).
The second suggestion can be very helpful for legacy data without fieldmaps. Of course, if you can have 3dshore pipeline published soon at least I would be glad to disregard eddy and switch to it :)

BTW, would it matter if the data only has one b0 volume for the 3dshore pipeline?
