### ISSUE TITLE
[ENH] Adding optional atlases

### ISSUE THREAD

**Issue by xiaosonghe** [PennBBL/qsiprep#32]
During reconstruction, for the pre-defined pipelines, it would be helpful that the users can choose the atlas(es) of their interest.
In addition to existing Schaefer 17 RSN version, I would recommend to add:
(1) Schaefer 7 RSN version;
(2) AICHA (a functionally defined symmetric atlas);
(3) Human Brainnetome Atlas (a multimodally defined atlas);
(4) Maybe Lausanne for what it worths???

And in the future perhaps Glasser's, when it's feasible...

**Comment by mattcieslak** [comment]
It's not documented, but at the moment these are the available atlases:

 - gordon333
 - power264
 - schaefer100
 - schaefer200
 - schaefer400
 - aal116

I don't think the power264 atlas makes a lot of sense for structural connectivity, but it's there nonetheless.

**Comment by xiaosonghe** [comment]
I agree that power264 seems to be odd since it's sphere based, right?
And also, have you noticed that other than the AAL, most of the atlases do not have subcortical components?
In HCP they added Harvard-Oxford subcortical atlas to the surface based atlases. Do you want to do this?
Essentially, it would be helpful to allow users to add their own atlases, right? I don't think this has to be achieved anytime soon but it could be useful.

**Comment by mattcieslak** [comment]
It's actually possible to add your own atlases, but this is also not documented. Could you open another issue for this?
