### ISSUE TITLE
anatomical ResampleInputSpecs voxel_size is 3x(None)

### ISSUE THREAD

**Issue by WillForan** [PennBBL/qsiprep#36]
I'm not sure where to start looking for the error. I've already resolved some symlink issues that might be surfing again.

>     Running qsiprep version 0+unknown:
>
>       * BIDS dataset path: /data.
>       * Participant list: ['10195', '10843', '10880', '10985', '10990', '10997', '11048', '11228', >'11248', '11270', '11272', '11275', '11289', '11299', '11314', '11338', '11346', '11370', '11389', '11393'].
>       * Run identifier: 20191021-210100_cbf64372-5fcb-4e65-892b-001a40cc4631.
>     
> Process Process-2:
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
>     self.run()
>   File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 794, in build_qsiprep_workflow
>     force_syn=opts.force_syn
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 241, in init_qsiprep_wf
>     force_syn=force_syn)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 507, in init_single_subject_wf
>     num_t1w=len(subject_data['t1w']))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/anatomical.py", line 276, in init_anat_preproc_wf
>     template_image=ref_img)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/anatomical.py", line 928, in init_output_grid_wf
>     resample_to_voxel_size.inputs.voxel_size = (voxel_size, voxel_size, voxel_size)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
>     value )
> traits.trait_errors.TraitError: The 'voxel_size' trait of a ResampleInputSpec instance must be a tuple of the form: (a float, a float, a float), but a value of (None, None, None) <class 'tuple'> was specified.

Command is:
```
docker run --rm -it -v $FREESURFER_HOME:$FREESURFER_HOME:ro -v /Volumes:/Volumes:ro -v /Volumes/Hera/Raw/BIDS/mMRDA-dev:/data:ro -v /Volumes/Hera/Projects/mMR_PETDA/qsi_test:/out pennbbl/qsiprep:0.6.1 --bids-dir /data --output-dir /out --analysis-level participant --fs-license-file  $FREESURFER_HOME/license.txt -w /out/workdir
```

An example t1.json

```
jq < sub-10195/ses-20160317/anat/sub-10195_ses-20160317_acq-1ADNIG2_run-2_T1w.json
{
  "Modality": "MR",
  "MagneticFieldStrength": 3,
  "ImagingFrequency": 123.227,
  "Manufacturer": "Siemens",
  "ManufacturersModelName": "Biograph_mMR",
  "InstitutionName": "UPMC_Presbyterian_University_Hospital",
  "InstitutionalDepartmentName": "MR_Research_Center",
  "InstitutionAddress": "Lothrop_Street_200_Pittsburgh_Pennsylvania_Pittsburgh_-_Columbus_US_15213",
  "DeviceSerialNumber": "51021",
  "StationName": "MRC51021",
  "PatientPosition": "HFS",
  "ProcedureStepDescription": "BRAIN_lun-neuro",
  "SoftwareVersions": "syngo_MR_B20P",
  "MRAcquisitionType": "3D",
  "SeriesDescription": "Sagittal_MPRAGE_ADNI_G2",
  "ProtocolName": "Sagittal_MPRAGE_ADNI_G2",
  "ScanningSequence": "GR_IR",
  "SequenceVariant": "SP_MP",
  "ScanOptions": "IR",
  "SequenceName": "_tfl3d1_ns",
  "ImageType": [
    "ORIGINAL",
    "PRIMARY",
    "M",
    "ND",
    "NORM"
  ],
  "SeriesNumber": 10,
  "AcquisitionTime": "09:20:41.865000",
  "AcquisitionNumber": 1,
  "SliceThickness": 1,
  "SAR": 0.0627606,
  "EchoTime": 0.00298,
  "RepetitionTime": 2.3,
  "InversionTime": 0.9,
  "FlipAngle": 9,
  "PartialFourier": 1,
  "BaseResolution": 256,
  "ShimSetting": [
    -5752,
    -7306,
    1610,
    -109,
    -375,
    -845,
    -591,
    293
  ],
  "TxRefAmp": 294.031,
  "PhaseResolution": 1,
  "ReceiveCoilName": "HeadNeck_MRPET",
  "CoilString": "t:HEA;HEP;NEA;NEP",
  "PulseSequenceDetails": "%SiemensSeq%_tfl",
  "RefLinesPE": 24,
  "PercentPhaseFOV": 93.75,
  "PhaseEncodingSteps": 239,
  "AcquisitionMatrixPE": 240,
  "ReconMatrixPE": 240,
  "PixelBandwidth": 238,
  "DwellTime": 8.2e-06,
  "ImageOrientationPatientDICOM": [
    0,
    1,
    0,
    0,
    0,
    -1
  ],
  "InPlanePhaseEncodingDirectionDICOM": "ROW",
  "ConversionSoftware": "dcm2niix",
  "ConversionSoftwareVersion": "v1.0.20190410  (JP2:OpenJPEG) GCC8.3.0"
}

```

**Comment by mattcieslak** [comment]
Hi Will, you need to `--output-resolution`. This is not a helpful error message, so I'm going to open an issue for that. What symlink issues were you having earlier?

**Comment by WillForan** [comment]
Thanks! Sorry I missed the obvious switch!

The link issue was totally on my end. The links point to absolute paths and docker wasn't able to see them with the default `qsiprep-docker` generated docker command. Adding `-v /Volumes:/Volumes:ro` was my aggressive solution.

In case this ends up in any search results, the message was

> Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
> 	1: [ERR] This file appears to be an orphaned symlink. Make sure it correctly points to its referent. (code: 43 - ORPHANED_SYMLINK)
> 	        ./sub-10195/ses-2016/anat/....
> 		... and 847 more files having this issue (Use --verbose to see them all).
