### ISSUE TITLE
FYI: adding qsiprep to bids-apps listing

### ISSUE THREAD

**Issue by yarikoptic** [PennBBL/qsiprep#60]
see https://github.com/BIDS-Apps/bids-apps.github.io/pull/15
hopefully that would be sufficient

**Comment by akhanf** [comment]
Somewhat related to this, but the BIDS app standard also specifies that the bids, output and analysis_level arguments should be positional (and not require the current options: `--bids_dir data/bids_root/ --output_dir out/ --analysis_level participant`). Those options are incompatible with our local bids-app launchers and I am guessing would affect others as well?

**Comment by yarikoptic** [comment]
I think this would be worth a dedicated issue, and ideally addressed to stay Kosher (i.e. "bids-app standard compliant").

**Comment by mattcieslak** [comment]
the argument parser was not working reliably with the mixture of positional and flag arguments. Added an issue #63

**Comment by mattcieslak** [comment]
This got fixed in v0.6.4-1
