### ISSUE TITLE
Longitudinal reports don't have DWI svgs

### ISSUE THREAD

**Issue by araikes** [PennBBL/qsiprep#64]
I ran `qsiprep:0.6.4` on my longitudinal dataset. 

The HTML reports have the T1w SVGs embedded but the DWI SVGs are not included. There's a hyperlink for them and I can load them in a separate browser tab that way. However, they aren't embedded in the report even though the paths exist.

**Comment by araikes** [comment]
On a related note:
If one session has a reverse phase encoded image and the other session does not, TOPUP will run on the session with the RPE and obviously not on the other session. The SVG file for the SDC will be generated for the TOPUP session but the report will not include the section for the image.

I hope that's clear. If not, I don't mind sharing the report. The T1s I'm using aren't currently face-stripped but I could send you the outputs and report if you have a dropbox-y way for me to do so.

**Comment by mattcieslak** [comment]
The reports system is based on the old fmriprep (1.2.6) code and I'm not sure why this occasionally happens. I've noticed that sometimes the svgs don't load in the page, particularly if there was an error during the workflow. The reports system definitely need an update. I'll open a PR for this
