### ISSUE TITLE
Error in combine_all_dwis

### ISSUE THREAD

**Issue by italab03** [PennBBL/qsiprep#68]
Thank you for sharing this great app!
I tried to apply qsiprep on my NODDI data (two runs with different PE) and faced the following errors:

Have you seen this error before?

> qsiprep-docker --bids_dir /home/test/OCEAN/sourcedata --output_dir /home/test/OCEAN/derivatives/Preprocessed --analysis_level participant -w /home/test/OCEAN/derivatives/Preprocessed --fs-license-file /usr/local/freesurfer/license.txt  --skip_bids_validation --output-space T1w --output-resolution 1.3 --force-spatial-normalization --write-graph --participant_label 00250201 --b0-threshold 100 --hmc-model eddy --denoise-before-combining --combine_all_dwis
> ['/home/test/.pyenv/versions/3.6.3/bin/qsiprep-docker', '--bids_dir', '/home/test/OCEAN/sourcedata', '--output_dir', '/home/test/OCEAN/derivatives/Preprocessed', '--analysis_level', 'participant', '-w', '/home/test/OCEAN/derivatives/Preprocessed', '--fs-license-file', '/usr/local/freesurfer/license.txt', '--skip_bids_validation', '--output-space', 'T1w', '--output-resolution', '1.3', '--force-spatial-normalization', '--write-graph', '--participant_label', '00250201', '--b0-threshold', '100', '--hmc-model', 'eddy', '--denoise-before-combining', '--combine_all_dwis']
> RUNNING: docker run --rm -it -v /usr/local/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /home/test/OCEAN/sourcedata:/data:ro -v /home/test/OCEAN/derivatives/Preprocessed:/out -v /home/test/OCEAN/derivatives/Preprocessed:/scratch pennbbl/qsiprep:0.6.4 --bids-dir /data --output-dir /out --analysis-level participant --skip_bids_validation --output-space T1w --output-resolution 1.3 --force-spatial-normalization --write-graph --participant_label 00250201 --b0-threshold 100 --hmc-model eddy --denoise-before-combining --combine_all_dwis -w /scratch
> 191108-01:56:31,124 nipype.workflow IMPORTANT:
> 	 
>     Running qsiprep version 0.6.4:
>       * BIDS dataset path: /data.
>       * Participant list: ['00250201'].
>       * Run identifier: 20191108-015629_524b7887-dacd-4cc8-a31b-e8c77ee57486.
>     
> 191108-01:56:34,307 nipype.workflow INFO:
> 	 Combining all 2 dwis within the single available session
> 191108-01:56:34,307 nipype.workflow INFO:
> 	 [['/data/sub-00250201/dwi/sub-00250201_dir-AP_dwi.nii.gz', '/data/sub-00250201/dwi/sub-00250201_dir-PA_dwi.nii.gz']]
> 191108-01:56:35,641 nipype.workflow INFO:
> 	 The following DWI files were found with the following fieldmaps:
>  * /data/sub-00250201/dwi/sub-00250201_dir-AP_dwi.nii.gz (PEDir j-): /data/sub-00250201/fmap/sub-00250201_dir-PA_epi.nii.gz (Type epi)
>  * /data/sub-00250201/dwi/sub-00250201_dir-PA_dwi.nii.gz (PEDir j): /data/sub-00250201/fmap/sub-00250201_dir-AP_epi.nii.gz (Type epi)
> 
> The following warped spaces were defined to contain:
>  * PEDir: j-, fmap: /data/sub-00250201/fmap/sub-00250201_dir-PA_epi.nii.gz 
>     -> /data/sub-00250201/dwi/sub-00250201_dir-AP_dwi.nii.gz
>  * PEDir: j, fmap: /data/sub-00250201/fmap/sub-00250201_dir-AP_epi.nii.gz 
>     -> /data/sub-00250201/dwi/sub-00250201_dir-PA_dwi.nii.gz
> 
> The following warp groups were used to SDC each other
>   * A single group containing j/j- PE dir groups was sent to TOPUP
> 191108-01:56:35,725 nipype.workflow IMPORTANT:
> 	 Creating dwi processing workflow "dwi_preproc_wf" to produce output sub-00250201 (1.20 GB / 147 DWIs). Memory resampled/largemem=1.79/1.99 GB.
> Process Process-2:
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
>     self.run()
>   File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 839, in build_qsiprep_workflow
>     force_syn=opts.force_syn
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 241, in init_qsiprep_wf
>     force_syn=force_syn)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/base.py", line 624, in init_single_subject_wf
>     sloppy=debug
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/dwi/base.py", line 308, in init_dwi_preproc_wf
>     omp_nthreads=omp_nthreads)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/dwi/pre_hmc.py", line 145, in init_dwi_pre_hmc_wf
>     ('b0_indices', 'b0_indices')])
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 214, in connect
>     '\n'.join(['Some connections were not found'] + infostr))
> Exception: Some connections were not found
> Module concat_rpe_splits has no input called original_files_plus
> 
> Module concat_rpe_splits has no input called original_files_minus
>

**Comment by mattcieslak** [comment]
You've found a bug! This should be `original_images_minus`. I will fix this before the next release

**Comment by mattcieslak** [comment]
Hi @italab03, could you try using version 0.6.5? This should be fixed. Thanks!

**Comment by italab03** [comment]
Hi thank you for fixing bug.

I tried version 0.6.5 and got the following errors:

> 191125-03:32:11,180 nipype.workflow ERROR:
> 	 could not run node: qsiprep_wf.single_subject_00250301_wf.dwi_preproc_wf.hmc_sdc_wf.prepare_rpe_b0
> QSIPrep failed: Workflow did not execute cleanly. Check log for details
> Traceback (most recent call last):
>   File "/usr/local/miniconda/bin/qsiprep", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 552, in main
>     qsiprep_wf.run(**plugin_settings)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 599, in run
>     runner.run(execgraph, updatehash=updatehash, config=self.config)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 191, in run
>     report_nodes_not_run(notrun)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/tools.py", line 82, in report_nodes_not_run
>     raise RuntimeError(('Workflow did not execute cleanly. '
> RuntimeError: Workflow did not execute cleanly. Check log for details
> Sentry is attempting to send 2 pending error messages
> Waiting up to 2 seconds
> Press Ctrl-C to quit
> 

The error messages are as follows:

> Node: qsiprep_wf.single_subject_00250301_wf.dwi_preproc_wf.hmc_sdc_wf.prepare_rpe_b0
> Working directory: /wd/qsiprep_wf/single_subject_00250301_wf/dwi_preproc_wf/hmc_sdc_wf/prepare_rpe_b0
> 
> Node inputs:
> 
> b0_file = ['/bids_data/sub-00250301/dwi/sub-00250301_dir-PA_dwi.nii.gz']
> b0_threshold = 100
> max_num_b0s = 3
> orientation = LAS
> output_3d_images = False
> 
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
>     result['result'] = node.run(updatehash=updatehash)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 375, in run
>     runtime = self._run_interface(runtime)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/fmap.py", line 74, in _run_interface
>     self.inputs)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/fmap.py", line 154, in _get_b0s_and_metadata
>     if np.any(bvals > b0_threshold):
> TypeError: '>' not supported between instances of 'float' and 'B0RPEFieldmapInputSpec'

How I can fix this? Thank you for your efforts and help!
