### ISSUE TITLE
bidsmap/json setup

### ISSUE THREAD

**Issue by dpagliaccio** [PennBBL/qsiprep#69]
Hello,
I am getting data setup to process with QSIprep and was wondering if there were any requirements/recommendations in setting up the json files for DTI & accompanying field maps, i.e. necessary parameters, customLabels, etc. to include in the dcm2bids config file?
Thanks!

**Comment by mattcieslak** [comment]
Hi! I'm not familiar with dcm2bids, but some of the things you'll want to make sure you have correct are

 * The phase encoding direction in your dwi images and fieldmaps
 * The fields required for calculating Effective Echo Spacing (https://github.com/PennBBL/qsiprep/blob/44be045c83d4aaf5fdbcf8817c0ea986f528ae25/qsiprep/interfaces/fmap.py#L459)
 * The `"IntendedFor"` fields in the fieldmap images.

Although it's possible to skip BIDS validation, I strongly recommend against it. The best path is to make sure your data passes the BIDS validator then to try QSIPrep on a single subject to see if it is detecting and applying the fieldmaps correctly.

**Comment by mattcieslak** [comment]
Unless you have any follow-up questions I'm going to close this for now
