### ISSUE TITLE
Empty CNR outputs

### ISSUE THREAD

**Issue by araikes** [PennBBL/qsiprep#72]
Hi @mattcieslak,
I haven't seen this issue mentioned yet. I've tested it with `qsiprep:0.6.4` on both cross-sectional and longitudinal data with single and multishell acquisitions.

Everyone gets a `desc-eddy_cnr.nii.gz` file. However this is an empty file. The dimensions appear right when I `mrinfo` (97x116x98) but its just a blank image with a mean value of 0 (`fslstats *eddy_cnr.nii.gz -m`)?

Working as intended or bug?

**Comment by mattcieslak** [comment]
Thanks for pointing this out. I think this is a result of the reorientation that happened in 0.6.3. Should be an easy fix.
