### ISSUE TITLE
[ENH] Consistently define how images are assigned as b=0

### ISSUE THREAD

**Issue by mattcieslak** [PennBBL/qsiprep#8]
There isn't currently a consistently-applied heuristic or a user option for what should count as a b=0 image. Reported by @dpys.

Considering copying DSI Studio and just setting the threshold to b=100 everywhere.

**Comment by clintg6** [comment]
Dipy sets their threshold at 50 but also allows it as a parameter but the default is anything below 50 is declared a b0.

**Comment by mattcieslak** [comment]
there is a commandline flag for this now: `--b0-threshold`
