### ISSUE TITLE
N4 error and pre_topup_enhance.n4_correct

### ISSUE THREAD

**Issue by madrig8l** [PennBBL/qsiprep#89]
Dear all,

I am running the preprocessing pipeline (0.6.6) for the first time (docker container) and am receiving an error report from N4. I am aware that this was addressed previously, but am not sure how to fix it. The crash report is attached below. 

The pipeline continues after this error but stops after eddy giving this report:

200104-13:50:21,523 nipype.workflow ERROR:
 could not run node: qsiprep_wf.single_subject_01_wf.dwi_preproc_ses_01_wf.hmc_sdc_wf.pre_topup_enhance.n4_correct

I'm not sure if these issues are related, any advice would be appreciated! I can also provide my input data if that helps.

Bastian

Crash report from N4:

Node: qsiprep_wf.single_subject_01_wf.dwi_preproc_ses_01_wf.hmc_sdc_wf.pre_topup_enhance.n4_correct
Working directory: /scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/pre_topup_enhance/n4_correct

Node inputs:

args = -v 1
bias_image = <undefined>
bspline_fitting_distance = 150.0
bspline_order = 3
convergence_threshold = 1e-06
copy_header = True
dimension = 3
environ = {'NSLOTS': '1'}
input_image = /scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/pre_topup_enhance/rescale_image/vol0000_LPS_TruncateImageIntensity_RescaleImage.nii.gz
mask_image = <undefined>
n_iterations = [200, 200]
num_threads = 1
output_image = <undefined>
save_bias = False
shrink_factor = <undefined>
weight_image = /scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/pre_topup_enhance/fix_smooth_mask_header/vol0000_LPS_TruncateImageIntensity_mask_FillHoles_MD_G_fixhdr.nii.gz

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/ants/segmentation.py", line 438, in _run_interface
    runtime, correct_return_codes)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 758, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 695, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
N4BiasFieldCorrection -v 1 --bspline-fitting [ 150, 3 ] -d 3 --input-image /scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/pre_topup_enhance/rescale_image/vol0000_LPS_TruncateImageIntensity_RescaleImage.nii.gz --convergence [ 200x200, 1e-06 ] --output vol0000_LPS_TruncateImageIntensity_RescaleImage_corrected.nii.gz --weight-image /scratch/qsiprep_wf/single_subject_01_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/pre_topup_enhance/fix_smooth_mask_header/vol0000_LPS_TruncateImageIntensity_mask_FillHoles_MD_G_fixhdr.nii.gz
Standard output:

Running N4 for 3-dimensional images.

Mask not read.  Using the entire image as the mask.

Original intensity range:  [0, 1000]

***********************************************************
Warning:  Your input image contains nonpositive values
which could cause failure or problematic results.  A
possible workaround would be to:
   1. rescale your image to positive values e.g., [10,100].
   2. run N4 on your rescaled image.
   3. (optional) rescale the N4 output to the original
      intensity range.
***********************************************************

Specified spline distance: 150mm
  original image size:  [128, 104, 75]
  padded image size:  [151, 151, 76]
  number of control points:  [5, 5, 4]

Standard error:
Exception caught: 
itk::ExceptionObject (0xfcf5a0)
Location: "unknown" 
File: /tmp/ants/build/staging/include/ITK-5.1/itkImageToImageFilter.hxx
Line: 220
Description: itk::ERROR: N4BiasFieldCorrectionImageFilter(0xfc0700): Inputs do not occupy the same physical space! 
InputImage Origin: [-1.2752269e+02, -9.4468857e+01, -5.6481712e+01], InputImageMaskImage Origin: [-1.2752263e+02, -9.4468856e+01, -5.6481712e+01]
	Tolerance: 8.0000000e-06
InputImage Direction: 9.9997757e-01 -3.5859259e-08 -6.6981985e-03
2.0573588e-03 9.5166242e-01 3.0713907e-01
6.3744130e-03 -3.0714595e-01 9.5164107e-01
, InputImageMaskImage Direction: 9.9997769e-01 1.2041110e-04 -6.6792433e-03
1.9369119e-03 9.5166254e-01 3.0713948e-01
6.3933687e-03 -3.0714557e-01 9.5164107e-01

	Tolerance: 1.0000000e-06
Return code: 1

**Comment by mattcieslak** [comment]
Thanks for reporting this! This bug has been popping up all over the place. That whole workflow is being reworked in #83. I will follow up when this gets merged.

**Comment by mattcieslak** [comment]
@madrig8l  could you let me know if this works for you in version 0.8.0RC2?

**Comment by fredrmag** [comment]
I encountered the same bug as @madrig8l in version 0.6.6-1. 

I downloaded version 0.8.0RC2 and I am not encountering the error. So, the bug seems resolved. Thanks for fixing!

**Comment by madrig8l** [comment]
I have not been able to try the new version yet, but will get back to you
as soon as I can!

Thank you for your help so far,
Bastian

**Comment by madrig8l** [comment]
Dear Matt, I can confirm now that the error was resolved in version 0.8.0!

Thank you very much!

Bastian
